### ISSUE TITLE
vkaci pod constantly crashes

### ISSUE THREAD

**Issue by joezersk** [datacenter/ACI-Kubernetes-Visualiser#19]
The vkaci pod crashes, backs off, tries again and keeps crashing.  

```
cisco@nkt-master-1:~$ kubectl get pods
NAME                     READY   STATUS             RESTARTS       AGE
goldpinger-brmtd         1/1     Running            1              39m
goldpinger-l4l4j         1/1     Running            1              39m
goldpinger-z2hpr         1/1     Running            1              39m
my-neo4j-0               1/1     Running            1              39m
vkaci-547fc784f9-wbswf   0/1     CrashLoopBackOff   15 (62s ago)   39m
```
logs show this condition...maybe something to do with LLDP

```
2022-10-07 11:50:38,916 graph INFO [ThreadPoolExecutor-0_1] Interface topology/pod-1/paths-2102/pathep-[eth1/31] is Bundled under topology/pod-1/protpaths-2101-2102/pathep-[VPC_KUBE02]
2022-10-07 11:50:38,986 graph INFO [ThreadPoolExecutor-0_0] Found the following Host as Neighbour
2022-10-07 11:50:38,987 graph INFO [ThreadPoolExecutor-0_0] Found leaf-2101 as Neighbour to :
2022-10-07 11:50:39,024 graph INFO [ThreadPoolExecutor-0_1] Found the following Host as Neighbour
2022-10-07 11:50:39,024 graph INFO [ThreadPoolExecutor-0_1] Found leaf-2101 as Neighbour to :
2022-10-07 11:50:39,026 graph INFO [ThreadPoolExecutor-0_2] Found the following Host as Neighbour
2022-10-07 11:50:39,026 graph INFO [ThreadPoolExecutor-0_2] Found leaf-2101 as Neighbour to :
[2022-10-07 11:50:39 +0000] [7] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/visibility_ui.py", line 15, in <module>
    graph.update_database()
  File "/app/graph.py", line 635, in update_database
    topology = self.topology.update()
  File "/app/graph.py", line 521, in update
    result = future.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/graph.py", line 377, in update_node
    self.add_neighbour(node, lldp_neighbour)
  File "/app/graph.py", line 221, in add_neighbour
    if 'VMware' in neighbour_description:
TypeError: argument of type 'NoneType' is not iterable
```
Checking physical interface on the ESXi host where all this runs, I do see that LLDP is working

Link Layer Discovery Protocol from vCenter View
--
```
Chassis ID | 00:3a:9c:7b:f0:9f
Port ID | Eth1/31
Time to live | 117
TimeOut | 30
Samples | 39
Management Address | 10.50.129.212
Port Description | topology/pod-1/protpaths-2101-2102/pathep-[VPC_KUBE02]
System Description | topology/pod-1/node-2101
System Name | leaf-2101
```

Happy to provide lab access for internal people.

**Comment by joezersk** [comment]
More info if it helps...

```
cisco@nkt-master-1:~$ sudo crictl images
IMAGE                                           TAG                 IMAGE ID            SIZE
docker.io/bloomberg/goldpinger                  v3.5.1              79b8092fd6e48       81MB
docker.io/calico/cni                            v3.22.0             f86797de8afdf       236MB
docker.io/calico/kube-controllers               v3.22.0             df76d42861eec       133MB
docker.io/calico/node                           v3.22.0             f109b1742d349       217MB
docker.io/calico/pod2daemon-flexvol             v3.22.0             59daef946c8c6       21.5MB
docker.io/calico/typha                          v3.22.0             35c2fa1ee0a17       128MB
docker.io/cloudnativelabs/kube-router           v1.5.0              369cee4d18d9b       104MB
docker.io/kubernetesui/dashboard                v2.2.0              5c4ee6ca42ce2       228MB
docker.io/kubernetesui/metrics-scraper          v1.0.6              48d79e554db69       34.6MB
docker.io/library/haproxy                       latest              d9156375cc8d5       105MB
docker.io/library/neo4j                         4.4.3               67b0b4d3c8080       578MB
docker.io/library/redis                         3.2.12              87856cc39862c       79.2MB
gcr.io/google-samples/gb-redisslave             v3                  83e578f88cf4e       103MB
gcr.io/google_samples/gb-frontend               v6                  b16d7c8842b32       382MB
k8s.gcr.io/coredns/coredns                      v1.8.6              a4ca41631cc7a       47MB
k8s.gcr.io/etcd                                 3.5.3-0             aebe758cef4cd       301MB
k8s.gcr.io/ingress-nginx/controller             v1.1.1              2461b2698dcd5       289MB
k8s.gcr.io/ingress-nginx/kube-webhook-certgen   v1.1.1              c41e9fcadf5a2       49.1MB
k8s.gcr.io/kube-apiserver                       v1.24.2             d3377ffb7177c       131MB
k8s.gcr.io/kube-controller-manager              v1.24.2             34cdf99b1bb3b       121MB
k8s.gcr.io/kube-proxy                           v1.24.2             a634548d10b03       112MB
k8s.gcr.io/kube-scheduler                       v1.24.2             5d725196c1f47       52.3MB
k8s.gcr.io/metrics-server/metrics-server        v0.4.2              17c225a562d97       61.8MB
k8s.gcr.io/pause                                3.7                 221177c6082a8       718kB
quay.io/camillo/keepalived                      latest              55559b93da053       67.6MB
quay.io/camillo/vkaci-init                      1.0                 fa9500a2f0707       142MB
quay.io/camillo/vkaci                           1.0                 d94b0baf56a52       705MB
```

**Comment by samiib** [comment]
Thank you for trying out VKACI and finding an edge case we haven’t encountered before. 

The problem you found occurs when we can’t find either `sysDesc` or `ver` on any neighbour (eg.  lldpAdjEp). In this case the description variable becomes `None`. In Python iterating over `None` results in this error.

I have added a change and a new unit test for the edge case. Although, the change will resolve the crash it may also result in a topology where the interface and the neighbour descriptions are blank. We rely on these properties to determine how to find the VM host interface information. Based on your fabric I believe you are using UCS and if you were able to configure the `sysDesc` of the LLDP Neighbour to include the word “Cisco”, I believe this may also solve the problem.

**Comment by joezersk** [comment]
Samita, thanks for the pointer.  I am in fact using a UCS C-series rack server with a Cisco VIC.  Strangely enough, in CIMC, you enable LLDP to work by unticking the LLDP Enable Box (to off) in the NIC settings.  Now LLDP name and description fields are being exchanged and the vkaci pod is now working.
